version: '3'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: dev_user
      POSTGRES_DB: mpk
  server:
    container_name: "mpk_server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src/
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - TEMPLATING_PATH_TO_TEMPLATES=/app/src/templates/
    entrypoint: "sanic src.server.app --host 0.0.0.0 --port 8080 --dev"
