version: '3'
services:
  server:
    container_name: "mpk_server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/
    entrypoint: "sanic src.server.app --host 0.0.0.0 --port 8080 --dev"
